version: 0.1.{build}
skip_tags: true
os: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 2
test: off
branches:
  only:
  - master
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: LTJUAbG51ZPCn02tphWKlD6lVpm6DOgW9LUYAoR0g6QpVKFRMSCMMgjZxWPXcaLs
before_build:
  - nuget restore
  - ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }
before_package:
  - ps: Remove-Item packages\OpenCover* -include ("*.pdb", "*.sln", "*.csproj") -recurse
after_test: 
    - ps: .\CreateCoverage.ps1
build:
  project: Dapplo.Owin.sln
  publish_nuget: true
  publish_nuget_symbols: false
  verbosity: minimal
artifacts:
- path: '*.nupkg'
  name: NuGet package
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: 0+4uMr/wsyh8BisfHCwkDbaWwzmKNvvB2MwFz45/ePwbOMB6WT1AfhzujeddcN/2
  on:
    branch: master
    is_not_pr: true
    appveyor_repo_commit_message_extended: /\[release\]/
